# Generated by Django 4.2.7 on 2023-11-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='challenges',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress_update',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
