# Generated by Django 4.2.7 on 2023-11-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
