# Generated by Django 4.2.7 on 2023-11-16 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
