# Generated by Django 4.2.7 on 2023-11-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_appointment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
    ]
