# Generated by Django 4.2.7 on 2023-11-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
